### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by gazedash** [tanguyantoine/react-native-music-control#266]
# Description
Context.startForegroundService() did not then call Service.startForeground()
#159

Often happens on Samsung, 9.0 android version
I have 
```<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />``` in my manifest.

I use the latest version of react-native-music-control ("0.10.4")

1. Sample code (provide repo url or sample code)

2. Platform ?

   - [ ] iOS
   - [X] Android
   
   
3. Device
  - [ ] Simulator
  - [X] Real device

**Comment by dengue8830** [comment]
i'm facing the same, @gazedash do you solve it?

**Comment by hiennguyen92** [comment]
Got the same issue, I tried many workaround but can't solved completely

**Comment by marf** [comment]
Same problem here!

**Comment by fjmorant** [comment]
same 👍

**Comment by garfiaslopez** [comment]
+1

**Comment by benoitvogel** [comment]
Same problem here. Android 10 in an emulator.

Crashes consistently when calling setNowPlaying() after either resetNowPlaying() or stopControl().

**Comment by bunmiedee** [comment]
Turns out that the conditional block in MusicControlNotification onCreate method isn't necessary. 

```public void onCreate() {
            super.onCreate();
            notification = MusicControlModule.INSTANCE.notification.prepareNotification(MusicControlModule.INSTANCE.nb, false);
            startForeground(NOTIFICATION_ID, notification);
            isRunning = true;
        }```

**Comment by tanguyantoine** [comment]
reproducible with `0.10.8`?

**Comment by zatloeri** [comment]
> reproducible with `0.10.8`?

@tanguyantoine Yes, still getting this error on some hw devices in 0.10.8.
I think it started happening after I started calling `resetNowPlaying()` or `stopControl()` shortly after app start.

Maybe that is my mistake, cause I am not sure how to correctly start the control. When I enable control using `enableControl('play', true)` and `on(Command.play, () => {})` right before `setNowPlaying({...})` it does not show the given controll and if I do it on app start then it shows it too early.

**Comment by pabloluz** [comment]
Same issue here. I'm on `0.11.0`.

**Comment by pabloluz** [comment]
(Just realized many currently open issues might be related to this one, like #244, for example)

@tanguyantoine, I appreciate in advance your attention on that ;)

**Comment by tanguyantoine** [comment]
@bunmiedee would you mind creating a pull request ?

**Comment by bunmiedee** [comment]
@tanguyantoine sure - I can look into it over the weekend

**Comment by sparcbr** [comment]
While we don't fix this I'm using this workaround to prevent multiple calls to startForegroundService. Seems to stop the bug from happening.

```
--- a/android/src/main/java/com/tanguyantoine/react/MusicControlModule.java
+++ b/android/src/main/java/com/tanguyantoine/react/MusicControlModule.java
@@ -35,6 +35,7 @@ import java.net.URLConnection;
 import java.util.HashMap;
 import java.util.Locale;
 import java.util.Map;
+import androidx.core.content.ContextCompat;
 
 public class MusicControlModule extends ReactContextBaseJavaModule implements ComponentCallbacks2 {
     private static final String TAG = MusicControlModule.class.getSimpleName();
@@ -198,12 +199,7 @@ public class MusicControlModule extends ReactContextBaseJavaModule implements Co
 
         afListener = new MusicControlAudioFocusListener(context, emitter, volume);
 
-        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O){
-            context.startForegroundService(myIntent);
-
-        }
-        else
-            context.startService(myIntent);
+        ContextCompat.startForegroundService(context, myIntent);
 
         context.registerComponentCallbacks(this);
 
@@ -218,6 +214,10 @@ public class MusicControlModule extends ReactContextBaseJavaModule implements Co
 
         if (notification != null)
             notification.hide();
+
+        session.setActive(false);
+
+                /*
         session.release();
 
         ReactApplicationContext context = getReactApplicationContext();
@@ -239,6 +239,7 @@ public class MusicControlModule extends ReactContextBaseJavaModule implements Co
         nb = null;
 
         init = false;
+                */
     }
 
     synchronized public void destroy() {
```

**Comment by bradleyflood** [comment]
This was a problem for me too. Reopening to be fixed.

PRs welcome! @sparcbr @bunmiedee @pabloluz @gazedash

**Comment by bradleyflood** [comment]
Should be fixed in #329

**Comment by rborn** [comment]
@bradleyflood @bunmiedee  I still get this (a lot) with the latest version 😔

**Comment by rborn** [comment]
@bradleyflood @bunmiedee  I'll try this fix and make a PR if it works https://stackoverflow.com/a/53402038

**Comment by bradleyflood** [comment]
Thanks @rborn I'll reopen this issue.

**Comment by rborn** [comment]
Just a heads-up,  the above "fix" didn't work, we still have a lot of crashes on android 9/10  :(

**Comment by hiroyaiizuka** [comment]
any updates?
still get this error ...😣

**Comment by rborn** [comment]
Small update: we launched to prod with the changes done using the above fork and it seems to be fixed. I'll like to a few more days to be sure.

@natashache I have my fork where I merged your code 😻, synced with current master and added a small fix. Would you like to make a PR or can I do it? 😻   https://github.com/rborn/react-native-music-control

**Comment by rborn** [comment]
@bradleyflood I have been testing the fix in production and it seems to work fine, however I got no reply from @natashache nor @hiennguyen92  (https://github.com/natashache/react-native-music-control/commit/c28a931d589282473544c754ecaedc7f00ae4033#commitcomment-41838029) so I don't know how to proceed :(

**Comment by hiennguyen92** [comment]
@rborn You are free to use it at your disposal.

**Comment by rborn** [comment]
@hiennguyen92 thank you, I'll create a PR soon 😻

**Comment by rborn** [comment]
@bradleyflood PR done, can we maybe have a release 😅 ? This code is tested in production, we got no errors related to the startForeground anymore (there are some commits after that, which fix small issues but the crashes were only a few)

 @hiennguyen92,  @natashache thank you for your fixes 😻

**Comment by bradleyflood** [comment]
Thanks Dan. Let me check it out and get back to you.

Brad
