### ISSUE TITLE
Artwork from URL not showing up

### ISSUE THREAD

**Issue by jasongrishkoff** [tanguyantoine/react-native-music-control#51]
# Description
Just updated to the new version and artwork no longer showing up in the notification widget or as a background of lockscreen.

1. Sample code (provide repo url or sample code)

```
            MusicControl.setNowPlaying({
                title: song.title,
                artwork: 'https://i1.sndcdn.com/artworks-000210092462-ge99r2-t500x500.jpg',
                artist: song.artist,
                album: null,
                genre: null,
                duration: this.state.duration, // (Seconds)
                description: '', // Android Only
                color: 0xFFFFFF, // Notification Color - Android Only
                date: '1983-01-02T00:00:00Z', // Release Date (RFC 3339) - Android Only
                rating: 84 // Android Only (Percentage)
            })

```

2. Platform ?
   - [ ] iOS
   - [X ] Android
   
   
3. Device
  - [ X] Simulator
  - [X ] Real device

**Comment by Guichaguri** [comment]
It's definitely caused by #44. I'll investigate it.

**Comment by Guichaguri** [comment]
It's a really small change which was leaving URL artworks as null values.
It's fixed now, you might want to make this change manually over reinstalling it completely, it's pretty simple

**Comment by jasongrishkoff** [comment]
Made the change manually in node_modules/react-native-music-control/index.android.js,, did a gradle clean, ran react-native run-android and... it's still not showing artwork?

**Comment by Guichaguri** [comment]
It's showing for me. The [changes](https://github.com/tanguyantoine/react-native-music-control/compare/eedfb1cc90aa76b532a342b20f17e33028a38b37...master) after last npm publish didn't change anything else related to artworks.

Can you check if npm removed the code to match the published version?

**Comment by jasongrishkoff** [comment]
Can confirm, this issue has been resolved.
