### ISSUE TITLE
Now Playing Info not rendering

### ISSUE THREAD

**Issue by greglump** [tanguyantoine/react-native-music-control#9]
# Now Playing Info not rendering
I'm using react-native-sound for playing audio and was hoping to use this to handle the locked screen controls. I'm setting the audio using the example but getting the error below when the screen is locked.

So...it doesn't work at all 😞 . I'm guessing I'm doing something wrong with my configuration, or I need to do something with/like this `[[UIApplication sharedApplication] beginReceivingRemoteControlEvents];`

```
MusicControl.setNowPlaying({
    title: 'Billie Jean',
    artwork: 'http://lorempixel.com/400/400'
});
```

# Tasks

- [ ] resolve `Couldn't find the digitizer HID service` error (?)
- [ ] provide demo application

```
Jun 17 16:39:20 macinator-MBP SpringBoard[42649]: [MPUSystemMediaControls] Updating supported commands for now playing application.
Jun 17 16:39:29 macinator-MBP backboardd[42650]: Couldn't find the digitizer HID service, this is probably bad
Jun 17 16:39:29 --- last message repeated 1 time ---
Jun 17 16:39:29 macinator-MBP SpringBoard[42649]: *** error reading settings archive file: <ISRootSettings: /Users/macinator/Library/Developer/CoreSimulator/Devices/58684B94-0775-484F-BAD6-7CBD963FB7C2/data/Documents/com.apple.springboard.settings/ISRootSettings_10.plist> 
Jun 17 16:39:29 macinator-MBP SpringBoard[42649]: [MPUSystemMediaControls] Updating supported commands for now playing application.
Jun 17 16:39:29 macinator-MBP SpringBoard[42649]: Unable to load principle class from bundle with name NowPlayingArtLockScreen
Jun 17 16:39:29 macinator-MBP assertiond[42653]: assertion failed: 14F27 13C75: assertiond + 12188 [8CF1968D-3466-38B7-B225-3F6F5B64C552]: 0x1
Jun 17 16:39:29 macinator-MBP assertiond[42653]: Could not create or rename power assertion for <BKNewProcess: 0x7fbd90602970; org.reactjs.native.example.Podcastic; pid: 42751; hostpid: -1>: 0xe00002c9
Jun 17 16:39:29 macinator-MBP assertiond[42653]: assertion failed: 14F27 13C75: assertiond + 12188 [8CF1968D-3466-38B7-B225-3F6F5B64C552]: 0x1
Jun 17 16:39:29 macinator-MBP assertiond[42653]: Could not create or rename power assertion for <BKNewProcess: 0x7fbd90602970; org.reactjs.native.example.Podcastic; pid: 42751; hostpid: -1>: 0xe00002c9
Jun 17 16:39:29 macinator-MBP Podcastic[42751]:  ** -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] ** unhandled action -> <FBSSceneSnapshotAction: 0x7f9cc2b583e0> {
	    handler = remote;
	    info = <BSSettings: 0x7f9cc2b5b610> {
	        (1) = 5;
	    };
	}
Jun 17 16:39:29 macinator-MBP assertiond[42653]: Could not create or rename power assertion for <BKNewProcess: 0x7fbd90602970; org.reactjs.native.example.Podcastic; pid: 42751; hostpid: -1>: 0xe00002c9
Jun 17 16:39:29 macinator-MBP assertiond[42653]: assertion failed: 14F27 13C75: assertiond + 12188 [8CF1968D-3466-38B7-B225-3F6F5B64C552]: 0x1
Jun 17 16:39:29 macinator-MBP assertiond[42653]: Could not create or rename power assertion for <BKNewProcess: 0x7fbd90602970; org.reactjs.native.example.Podcastic; pid: 42751; hostpid: -1>: 0xe00002c9
```

**Comment by tanguyantoine** [comment]
Did you do all steps written in the README?

**Comment by greglump** [comment]
Yes I did.

Is there an example app somewhere?

**Comment by tanguyantoine** [comment]
Nop.  Is it a Java app or iOS app?

**Comment by greglump** [comment]
iOS. Do you have a half-baked example? Even just a snippet would be helpful.

**Comment by tanguyantoine** [comment]
```javascript
  componentDidMount() {
    MusicControl.enableBackgroundMode(true);
    MusicControl.on('play', ()=> {
      this.props.dispatch(playRemoteControl());
    })

    MusicControl.on('pause', ()=> {
      this.props.dispatch(pauseRemoteControl());
    })

    MusicControl.on('nextTrack', ()=> {
      this.props.dispatch(nextRemoteControl());
    })

    MusicControl.on('previousTrack', ()=> {
      this.props.dispatch(previousRemoteControl());
    })
  }
```

**Comment by tanguyantoine** [comment]
@greglump good?

**Comment by asommer70** [comment]
@tanguyantoine I am seeing this error too:

```
<FBSSceneSnapshotAction: 0x7fe8d520f430> {
    handler = remote;
    info = <BSSettings: 0x7fe8d5207a50> {
        (1) = 5;
    };
}
```

I have calls similar to what you gave in the example, but still don't see the player on the lock screen.  The player controls on the "button modal" do work though.

**Comment by tanguyantoine** [comment]
Did you checked in settings allow background playing?

https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

**Comment by asommer70** [comment]
@tanguyantoine yes here's my componentDidMount:

```
  componentDidMount() {
    MusicControl.enableBackgroundMode(true);
    MusicControl.enableControl('pause', true);
    MusicControl.enableControl('play', true);
    MusicControl.enableControl('togglePlayPause', true);
    MusicControl.enableControl('artwork', true);
    MusicControl.enableControl('skipForward', true, {interval: 5});
    MusicControl.enableControl('skipBackward', true, {interval: 5});

    MusicControl.on('play', ()=> {
      console.log('lock play...');
      this.play();
    })

    MusicControl.on('pause', ()=> {
      console.log('lock pause...');
      this.play();
      MusicControl.resetNowPlaying();
    })

    MusicControl.on('togglePlayPause', () => {
      console.log('lock play/pause...');
      // this.play();
    })

    MusicControl.on('skipBackward', () => console.log('skipBackward...'));
    MusicControl.on('skipForward', () => console.log('skipForward...'));
  }
```

**Comment by tanguyantoine** [comment]
@fastred any idea?

**Comment by asommer70** [comment]
@tanguyantoine quick update.  I updated by Xcode version to 7.3.1 (from 7.2) and the simulator to 9.3 and the error in Xcode went away.  Still not seeing the controls on the lock screen though.

**Comment by tanguyantoine** [comment]
I need to update the package version and republish the package. Can you try with a local copy ?

**Comment by asommer70** [comment]
Not 100% sure what you mean by a "local copy", but removed the *node_modules/react-native-music-control* and re-installed the with:

```
npm install --save tanguyantoine/react-native-music-control
```

Then removed and re-added the library in Xcode.  Same things though... the lower controls work, but nothing shows up on the main lock screen.

**Comment by tanguyantoine** [comment]
Can you share me your app, or create a new one and then send it to me ?

**Comment by asommer70** [comment]
Sure, it's [Audio Pila!](https://github.com/asommer70/audiopila-ios).  A small app to play audio files and sync playback location between devices.

**Comment by tanguyantoine** [comment]
You never mount, you Audios component so the componentDidMount is never called, rigth?

**Comment by asommer70** [comment]
It's mount by react-native-router-flux in the [src/main.js](https://github.com/asommer70/audiopila-ios/blob/master/src/main.js) file.

**Comment by tanguyantoine** [comment]
sorry ^^ i missed that. Will try asap and will try to figure out what's happening

**Comment by tanguyantoine** [comment]
i pushed

**Comment by asommer70** [comment]
I'm still not getting anything on the lock screen.  Is there something I need to change?

Thanks again @tanguyantoine for all your help.

**Comment by tanguyantoine** [comment]
https://github.com/asommer70/audiopila-ios/pull/1 can you try this?

**Comment by asommer70** [comment]
Still not showing up @tanguyantoine, at least in the simulator. Thanks for the pull request, I get how to enable background now.

I'll try it on hardware this evening.

Thanks again

**Comment by asommer70** [comment]
@tanguyantoine I created a new "bare bones" test project [here](https://github.com/asommer70/test_audio) and when using react-native-music-control with [react-native-sound](https://github.com/zmxv/react-native-sound) I still don't have controls on the lock screen.

Is there something I should do different when using react-native-sound?

Thanks again

**Comment by tanguyantoine** [comment]
Did you tried on a real device?

**Comment by asommer70** [comment]
@tanguyantoine apologies forgot I was going to try on hardware.  I tried the **test_audio** project on hardware and it totally worked fine.  I'll try in the **Audio Pila!** project and let you know how it goes.

Thanks again for all your help.

**Comment by tanguyantoine** [comment]
Great.

For other people : **TRY on physical hardware it does not works on simulator**
